from crewai import Agent
from dotenv import load_dotenv
import os
from tools.n8n_tool import PostSocialMediaTool

load_dotenv()

def create_social_media_manager_agent(ollama_llm):
    return Agent(
        role=\'Social Media Manager\',
        goal=\'Manage and optimize SymbioteSystems\' presence across all social media channels, driving engagement and growth.\',
        backstory=(
            "This agent is the public face of SymbioteSystems, meticulously handling all social media interactions. "
            "It schedules and publishes content generated by the Content Strategist, monitors engagement metrics, "
            "and actively responds to comments and direct messages to foster community. "
            "It tracks analytics to understand what resonates with the audience (HNWIs, executives, entrepreneurs, digital marketers) "
            "and provides feedback to the Content Strategist for continuous improvement. "
            "Its goal is to ensure a strong, consistent, and engaging brand presence across TikTok, Instagram, Facebook, X, Threads, Pinterest, and YouTube."
        ),
        verbose=True,
        allow_delegation=False,
        llm=ollama_llm,
        tools=[PostSocialMediaTool()]
    )
